import bcrypt from "bcryptjs";

const data = {
  users: [
    {
      name: 'Admin',
      email: 'admin@gmail.com',
      password: bcrypt.hashSync('1234', 8),
      isAdmin: true,
      isSeller: true,
      seller: {
        name: 'Puma',
        logo: '/images/logo1.png',
        description: 'best seller',
        rating: 4.5,
        numReviews: 120,
      },
    },
    {
      name: 'Dangg',
      email: 'user@gmail.com',
      password: bcrypt.hashSync('1234', 8),
      isAdmin: false,
    },
  ],

  products: [
    {
      //_id: '1',
      name: 'Nike Slim Shirt',
      category: 'Help-self',
      image: 'images/Book1.jpg',
      price: 120,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      //_id: '2',
      name: 'Adidas Fit Shirt',
      category: 'Help-self',
      image: 'images/Book2.jpg',
      price: 100,
      countInStock: 20,
      brand: 'Adidas',
      rating: 4.0,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      //_id: '3',
      name: 'Lacoste Free Shirt',
      category: 'Help-self',
      image: 'images/Book3.jpg',
      price: 220,
      countInStock: 0,
      brand: 'Lacoste',
      rating: 4.8,
      numReviews: 17,
      description: 'high quality product',
    },
    {
      //_id: '4',
      name: 'Nike Slim Pant',
      category: 'Help-self',
      image: 'images/Book4.jpg',
      price: 78,
      countInStock: 15,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 14,
      description: 'high quality product',
    },
    {
      //_id: '5',
      name: 'Puma Slim Pant',
      category: 'Help-self',
      image: 'images/Book5.jpg',
      price: 70,
      countInStock: 5,
      brand: 'Puma',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      //_id: '6',
      name: 'Adidas Fit Pant',
      category: 'Help-self',
      image: 'images/Book6.jpg',
      price: 139,
      countInStock: 12,
      brand: 'Adidas',
      rating: 4.5,
      numReviews: 15,
      description: 'high quality product',
    },
    {
      //_id: '7',
      name: 'Pumax Slim Pant',
      category: 'Help-self',
      image: 'images/Book7.jpg',
      price: 65,
      countInStock: 5,
      brand: 'Puma',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      //_id: '8',
      name: 'Nike Slim Panttt',
      category: 'Help-self',
      image: 'images/Book8.jpg',
      price: 78,
      countInStock: 15,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 14,
      description: 'high quality product',
    },
  ],
};
export default data;